--- #YAML:1.0
name:                Emacs-Run
version:             0.10
abstract:            use emacs from perl via the shell
license:             ~
author:              
    - Joseph Brenner <doom@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    base:                          0
    Class::Base:                   0.03
    Data::Dumper:                  0
    File::Basename:                0
    File::Copy:                    0
    File::Spec:                    0
    File::Temp:                    0
    Hash::Util:                    0
    IPC::Capture:                  0
    lib:                           0
    List::MoreUtils:               0
    List::Util:                    0
    strict:                        0
    Test::Differences:             0
    Test::More:                    0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
