# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Emacs-Run
version:      0.01
version_from: lib/Emacs/Run.pm
installdirs:  site
requires:
    base:                          0
    Class::Base:                   0.03
    Data::Dumper:                  0
    File::Basename:                0
    File::Copy:                    0
    Hash::Util:                    0
    lib:                           0
    List::MoreUtils:               0
    List::Util:                    0
    strict:                        0
    Test::Differences:             0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
